include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - 'lib/src/generated_plugin_registrant.dart'

linter:
  rules:
    depend_on_referenced_packages: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false