name: old_flutter_3_19_0
description: "An old project, created with Flutter 3.19.0 which is still supported by Wiredash"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0 <3.20.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  wiredash:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
